height: 1

linewidth: 1

zorder: 9

artists:
  artist0:
    - 
      style: sheet
      height: 1
      linewidth: 1
    - 
      style: sheet
      height: 0
      linewidth: 0

symbols:
  H:
    artist: artist1
    label: helix
  S:
    artist: artist0
    label: sheet
  L:
    artist: artist2
    label: loop
