drawstyle:
  height: 1.0
  linewidth: 0.7
  stride: 1.0
  zorder: 5
elements:
  H:
    label: Helix
    primitives:
    - HelixPrimitive-3e6c9a
    - HelixPrimitive-3497c5
  L:
    label: Loop
    primitives:
    - LinePrimitive-22d8e9
  S:
    label: Sheet
    primitives:
    - ArrowPrimitive-0644df
primitives:
  ArrowPrimitive-0644df:
    arrow_tip_length: 3
    fillcolor:
    - 0.87
    - 0.8
    - 0.0
    height_scalar: 0.65
    height_scalar2: 0.4
    linecolor:
    - 0.0
    - 0.0
    - 0.0
    linewidth_scalar: 1.0
    type: ArrowPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 1
  HelixPrimitive-3497c5:
    fill_inner_ribbon: true
    fillcolor:
    - 0.49
    - 0.16
    - 0.17
    height_scalar: 0.9
    linecolor:
    - 0.0
    - 0.0
    - 0.0
    linewidth_scalar: 1.0
    ribbon_period: 3.6
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: -0.1
  HelixPrimitive-3e6c9a:
    fill_inner_ribbon: false
    fillcolor:
    - 0.84
    - 0.15
    - 0.16
    height_scalar: 0.9
    linecolor:
    - 0.0
    - 0.0
    - 0.0
    linewidth_scalar: 1.0
    ribbon_period: 3.6
    ribbon_width: null
    type: HelixPrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 1
  LinePrimitive-22d8e9:
    fillcolor: w
    height_scalar: 1.0
    linecolor:
    - 0.12
    - 0.6
    - 0.12
    linewidth_scalar: 1.5
    type: LinePrimitive
    xy_offset:
    - 0
    - 0
    zorder_offset: 1
